pub enum Inst {
    Imm(u8),
    Add,
    Sub,
    Mul,
    Div,
    Left,
    Down,
    Up,
    Right,
    Nop,
}
impl Inst {
    pub fn new(key: char) -> Self {
        use Inst::*;
        match key {
            '\n' => Nop,
            '!' => Nop,
            '"' => Nop,
            '#' => Nop,
            '$' => Nop,
            '%' => Nop,
            '&' => Nop,
            '\'' => Nop,
            '(' => Nop,
            ')' => Nop,
            '*' => Mul,
            '+' => Add,
            ',' => Nop,
            '-' => Sub,
            '.' => Nop,
            '/' => Div,
            '0'..='9' => Imm(translate_hex_digit(key)),
            ':' => Nop,
            ';' => Nop,
            '<' => Nop,
            '=' => Nop,
            '>' => Nop,
            '?' => Nop,
            '@' => Nop,
            'A'..='Z' => Self::new(key.to_ascii_lowercase()),
            '[' => Nop,
            '\\' => Nop,
            ']' => Nop,
            '^' => Nop,
            '_' => Nop,
            '`' => Nop,
            'a'..='f' => Imm(translate_hex_digit(key)),
            'g' => Nop,
            'h' => Left,
            'i' => Nop,
            'j' => Down,
            'k' => Up,
            'l' => Right,
            'm' => Nop,
            'n' => Nop,
            'o' => Nop,
            'p' => Nop,
            'q' => Nop,
            'r' => Nop,
            's' => Nop,
            't' => Nop,
            'u' => Nop,
            'v' => Nop,
            'w' => Nop,
            'x' => Nop,
            'y' => Nop,
            'z' => Nop,
            '{' => Nop,
            '|' => Nop,
            '}' => Nop,
            '~' => Nop,
            _ => Nop,
        }
    }
}

fn translate_hex_digit(key: char) -> u8 {
    const ZERO: u8 = '0' as u8;
    const A: u8 = 'a' as u8;
    match key {
        '0'..='9' => key as u8 - ZERO + 0,
        'a'..='f' => key as u8 - A + 0xA,
        _ => unreachable!(),
    }
}
